# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2020. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
apiVersion: v2
publisher: ibm
name: wazi-debug
version: 1.1.0
type: VS Code extension
displayName: IBM Z Open Debug
title: IBM Z Open Debug
description: This VS Code extension provides support for IBM Z debugging, based on the IBM Z Open Debug extensions.
icon: https://raw.githubusercontent.com/IBM/zopendebug-about/master/images/ibm-z-open-debug.svg
repository: https://github.com/IBM/zopendebug-about.git
category: Language
firstPublicationDate: "2020-08-31"
spec:
  extensions:
  - https://github.com/nsharma1989/test-che/releases/download/1.0.0/zopendebug-profileui-1.0.0.vsix
