# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019, 2020. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
apiVersion: v2
publisher: IBM
name: zopeneditor
version: latest
type: VS Code extension
displayName: IBM Z Open Editor
title: IBM Z Open Debug
description: Provides Debug tools for IBM Z development.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/IBM/zopendebug-about.git
category: Language
firstPublicationDate: "2019-10-03"
  extensions:
  - https://github.com/nsharma1989/test-che/releases/download/1.0.0/zopendebug-profileui-1.0.0.vsix
